// Verified against the model config.json on 2026-09-27.
export const SKIN_MODEL_LABELS = [
  "Basal Cell Carcinoma",
  "Darier_s Disease",
  "Epidermolysis Bullosa Pruriginosa",
  "Hailey-Hailey Disease",
  "Herpes Simplex",
  "Impetigo",
  "Larva Migrans",
  "Leprosy Borderline",
  "Leprosy Lepromatous",
  "Leprosy Tuberculoid",
  "Lichen Planus",
  "Lupus Erythematosus Chronicus Discoides",
  "Melanoma",
  "Molluscum Contagiosum",
  "Mycosis Fungoides",
  "Neurofibromatosis",
  "Papilomatosis Confluentes And Reticulate",
  "Pediculosis Capitis",
  "Pityriasis Rosea",
  "Porokeratosis Actinic",
  "Psoriasis",
  "Tinea Corporis",
  "Tinea Nigra",
  "Tungiasis",
  "actinic keratosis",
  "dermatofibroma",
  "nevus",
  "pigmented benign keratosis",
  "seborrheic keratosis",
  "squamous cell carcinoma",
  "vascular lesion"
] as const
