ALTER TABLE "profiles"
ADD COLUMN IF NOT EXISTS "birthYear" INTEGER,
ADD COLUMN IF NOT EXISTS "province" TEXT,
ADD COLUMN IF NOT EXISTS "district" TEXT;

ALTER TABLE "services"
ADD COLUMN IF NOT EXISTS "durationMinutes" INTEGER NOT NULL DEFAULT 30;

ALTER TABLE "appointments"
ADD COLUMN IF NOT EXISTS "visitReason" TEXT,
ADD COLUMN IF NOT EXISTS "birthYear" INTEGER,
ADD COLUMN IF NOT EXISTS "province" TEXT,
ADD COLUMN IF NOT EXISTS "district" TEXT,
ADD COLUMN IF NOT EXISTS "payAtClinic" BOOLEAN NOT NULL DEFAULT false;
